version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    reviewers:
      - "SearrenFlamePark"
    labels:
      - "dependencies"
      - "frontend"
  - package-ecosystem: "npm" 
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "SearrenFlamePark"
    labels:
      - "dependencies"
