name: Sync Flamesphere to OpenAI Vector Store

on:
  push:
    branches: [ main ]
    paths:
      - '**.md'
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync Flamesphere to Vector Store
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Sync to Atticus Vector Store
      uses: shmatt/assistants-vector-store-sync@v1
      with:
        pattern: '**/*.md'
        token: ${{ secrets.OPENAI_API_KEY }}
        key: atticus-flamesphere
